spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
       - id: ORDER-SERVICE
         uri: http://localhost:9192
         predicates:
          - Path=/order/**
       - id: PAYMENT-SERVICE
         uri: http://localhohst:9191
         predicates:
           - Path=/payment/** 
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
server:
  port: 8989
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
