spring:
  application:
    name: Eureka-Registry

server:
  port: 8083
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8083/eureka 