spring:
  application:
    name: PAYMENT-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  cloud:
    config:
      enabled: false
server:
  port: 9191
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
    hostname: localhost

logging:
  file:
    name: D:/microservice.log 
